export const FETCH_POST_START="FETCH_POST_START";
export const FETCH_POST_SUCCESS = "FETCH_POST_SUCCESS";
export const FETCH_POST_FAIL="FETCH_POST_FAIL";
// users
export const FETCH_USERS_START= "FETCH_USERS_START";
export const FETCH_USERS_SUCCESS="FETCH_USERS_SUCCESS";
export const FETCH_USERS_FAIL="FETCH_USERS_FAIL";
// albums
export const FETCH_ALBUMS_START="FETCH_ALBUMS_START";
export const FETCH_ALBUMS_SUCCESS="FETCH_ALBUMS_SUCCESS";
export const FETCH_ALBUMS_FAIL ="FETCH_ALBUMS_FAIL";
